### ISSUE TITLE
primary Rust gdb development branch/repo?

### ISSUE THREAD

**Issue by m4b** [tromey/gdb#39]
There are a dizzying array of branches in gdb, and I'm also unfamiliar with its open source development process.

But basically:

1. when I'm running my gdb from my distro, say `GNU gdb (GDB) 8.0.1`, what branch was eventually used in its compilation, was it just whatever is in the 8.0.1 tag (if there is one?) and which upstream git repo would that be in?

2. Where would you say the major gdb development for rust features is taking place? Specifically I want to add things and also investigate some unusual behavior, and it looks like there's a lot of activity, but again the number of branches makes it hard.

If a lot of the features are taking place here,I'd propose collecting a list of the hot branches, or at least some fairly decent representative of what has a chance of going into the next tagged release of upstream gdb, as well as perhaps having future branches prefix `rust_` or something to easily disambiguate them.

Again, not sure if this is even the right place to bring this up...!

**Comment by tromey** [comment]
> when I'm running my gdb from my distro, say GNU gdb (GDB) 8.0.1, what branch was eventually used in its compilation, was it just whatever is in the 8.0.1 tag (if there is one?) and which upstream git repo would that be in?

Distros generally take something from the main gdb repository -- either a release or sometimes a branch (it's complicated but Fedora at least is sometimes a bit newer).  For upstream look here: https://sourceware.org/gdb/current/; git repo is git://sourceware.org/git/binutils-gdb.git.  gdb release branches tend to have names like "gdb-8.0-branch".

If you're doing development on gdb, just check out master from that repository.

> Where would you say the major gdb development for rust features is taking place?

Upstream.  gdb is primarily mailing-list based, so you would want to follow the "gdb-patches" mailing list.  There's also the file gdb/CONTRIBUTE in the source tree that might be reasonably accurate :)

gdb's bugzilla has some known Rust issues. See [the list](https://sourceware.org/bugzilla/buglist.cgi?component=rust&list_id=39596&product=gdb&resolution=---); but there are a couple I know of that I still haven't filed.  When a Rust bug is fixed, I just close it and set the target milestone to the next release; so you can search closed ones to see what might be fixed in the next release.

> If a lot of the features are taking place here

This is really just my personal repository where I stash things and sometimes develop features (but there's other stuff I never push...).  A few gdb folks have these.

I should probably go through and close all the issues here, those were from when I was working on the initial rust support -- but that's all landed upstream now.

> Again, not sure if this is even the right place to bring this up...!

Not technically but it doesn't matter :)

We should definitely coordinate our efforts.  You have to jump through hoops to get a new bugzilla account nowadays (spam...), but that would be a good way to go.  I'm working full-time on Rust debugging right now, but most of my time is taken up working on the lldb plugin.

**Comment by m4b** [comment]
Hey thanks so much for this response! I've run into a couple issues while investigating stuff related to the debugging issues i opened on rust repo; i'm starting to realize some of the issues also appear to be exacerbated by the gdb rust language support not working properly in some cases. I'll ping you with an example in a rustc PR in a little bit if you don't mind!

**Comment by tromey** [comment]
Finally closing this.  Feel free to ask questions here; but as noted before main development is upstream.
